version: "2"


services:
    app-server:
        image: wsucs3620/alpine-nginx-php7:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - /Users/Larson/Docker/final/src:/usr/share/nginx
        links:
            - mysql:mysql
            - redis:redis
        depends_on:
            - mysql
            - redis

    mysql:
        image: wsucs3620/alpine-mysql:latest
        ports:
            - 3306:3306
        volumes:
            - /Users/Larson/Docker/data/mysql:/data
        environment:
            - MYSQL_ROOT_PASSWORD=unibase
            - MYSQL_DATABASE=CS3620
            - MYSQL_USER=marco
            - MYSQL_PASSWORD=polo

    redis:
        image: wsucs3620/alpine-redis:latest
        ports:
            - 6379:6379
        volumes:
            - /Users/Larson/Docker/data/redis:/data
